[2024-05-17T20:59:27.336+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T20:59:27.387+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.save_file manual__2024-05-17T12:31:17.083416+00:00 [queued]>
[2024-05-17T20:59:27.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.save_file manual__2024-05-17T12:31:17.083416+00:00 [queued]>
[2024-05-17T20:59:27.405+0000] {taskinstance.py:2306} INFO - Starting attempt 10 of 10
[2024-05-17T20:59:27.426+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_file> on 2024-05-17 12:31:17.083416+00:00
[2024-05-17T20:59:27.439+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=11696) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T20:59:27.442+0000] {standard_task_runner.py:63} INFO - Started process 11718 to run task
[2024-05-17T20:59:27.442+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'save_file', 'manual__2024-05-17T12:31:17.083416+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmpscd308_y']
[2024-05-17T20:59:27.443+0000] {standard_task_runner.py:91} INFO - Job 100: Subtask save_file
[2024-05-17T20:59:27.520+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.save_file manual__2024-05-17T12:31:17.083416+00:00 [running]> on host e512d0910ba5
[2024-05-17T20:59:27.647+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='save_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T12:31:17.083416+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T12:31:17.083416+00:00'
[2024-05-17T20:59:27.648+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T20:59:27.706+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T20:59:27.707+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data-ingestion-dag.py", line 175, in save_file
    for result in validation_results["results"]:
                  ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-05-17T20:59:27.721+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_ingestion_pipelines_2, task_id=save_file, run_id=manual__2024-05-17T12:31:17.083416+00:00, execution_date=20240517T123117, start_date=20240517T205927, end_date=20240517T205927
[2024-05-17T20:59:27.740+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 100 for task save_file (string indices must be integers, not 'str'; 11718)
[2024-05-17T20:59:27.779+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-17T20:59:27.810+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-17T20:59:27.816+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
