[2024-05-17T20:31:18.809+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T20:31:18.860+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation manual__2024-05-17T12:31:17.083416+00:00 [queued]>
[2024-05-17T20:31:18.876+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation manual__2024-05-17T12:31:17.083416+00:00 [queued]>
[2024-05-17T20:31:18.877+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 5
[2024-05-17T20:31:18.901+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_based_on_validation> on 2024-05-17 12:31:17.083416+00:00
[2024-05-17T20:31:18.912+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9569) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T20:31:18.914+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'branch_based_on_validation', 'manual__2024-05-17T12:31:17.083416+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmprxjm7frw']
[2024-05-17T20:31:18.916+0000] {standard_task_runner.py:63} INFO - Started process 9583 to run task
[2024-05-17T20:31:18.917+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask branch_based_on_validation
[2024-05-17T20:31:18.997+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation manual__2024-05-17T12:31:17.083416+00:00 [running]> on host e512d0910ba5
[2024-05-17T20:31:19.155+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='branch_based_on_validation' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T12:31:17.083416+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T12:31:17.083416+00:00'
[2024-05-17T20:31:19.157+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T20:31:19.185+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-17T20:31:19.208+0000] {python.py:237} INFO - Done. Returned value was: ['save_data_errors', 'save_file']
[2024-05-17T20:31:19.209+0000] {branch.py:36} INFO - Branch into ['save_data_errors', 'save_file']
[2024-05-17T20:31:19.209+0000] {skipmixin.py:178} INFO - Following branch ['save_data_errors', 'save_file']
[2024-05-17T20:31:19.243+0000] {skipmixin.py:246} INFO - Skipping tasks []
[2024-05-17T20:31:19.262+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T20:31:19.290+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_ingestion_pipelines_2, task_id=branch_based_on_validation, run_id=manual__2024-05-17T12:31:17.083416+00:00, execution_date=20240517T123117, start_date=20240517T203118, end_date=20240517T203119
[2024-05-17T20:31:19.334+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-17T20:31:19.385+0000] {taskinstance.py:3498} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-05-17T20:31:19.389+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
