[2024-05-18T02:40:17.444+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T02:40:17.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T02:40:17.521+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T02:40:17.523+0000] {taskinstance.py:2306} INFO - Starting attempt 13 of 13
[2024-05-18T02:40:17.548+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_based_on_validation> on 2024-05-17 00:00:00+00:00
[2024-05-18T02:40:17.561+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4280) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T02:40:17.565+0000] {standard_task_runner.py:63} INFO - Started process 4294 to run task
[2024-05-18T02:40:17.564+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'branch_based_on_validation', 'scheduled__2024-05-17T00:00:00+00:00', '--job-id', '222', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmpd99xsz5a']
[2024-05-18T02:40:17.566+0000] {standard_task_runner.py:91} INFO - Job 222: Subtask branch_based_on_validation
[2024-05-18T02:40:17.654+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation scheduled__2024-05-17T00:00:00+00:00 [running]> on host 5ee845ef4e45
[2024-05-18T02:40:17.807+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='branch_based_on_validation' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T00:00:00+00:00'
[2024-05-18T02:40:17.809+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T02:40:17.833+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-18T02:40:17.850+0000] {python.py:237} INFO - Done. Returned value was: ['send_alerts', 'save_data_errors', 'save_file']
[2024-05-18T02:40:17.851+0000] {branch.py:36} INFO - Branch into ['send_alerts', 'save_data_errors', 'save_file']
[2024-05-18T02:40:17.851+0000] {skipmixin.py:178} INFO - Following branch ['send_alerts', 'save_data_errors', 'save_file']
[2024-05-18T02:40:17.893+0000] {skipmixin.py:246} INFO - Skipping tasks []
[2024-05-18T02:40:17.914+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T02:40:17.945+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_ingestion_pipelines_2, task_id=branch_based_on_validation, run_id=scheduled__2024-05-17T00:00:00+00:00, execution_date=20240517T000000, start_date=20240518T024017, end_date=20240518T024017
[2024-05-18T02:40:17.981+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-18T02:40:18.036+0000] {taskinstance.py:3498} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-05-18T02:40:18.040+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
