[2024-05-18T02:06:38.200+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T02:06:38.266+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T02:06:38.287+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T02:06:38.289+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-05-18T02:06:38.323+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_based_on_validation> on 2024-05-17 00:00:00+00:00
[2024-05-18T02:06:38.340+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1560) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T02:06:38.344+0000] {standard_task_runner.py:63} INFO - Started process 1575 to run task
[2024-05-18T02:06:38.343+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'branch_based_on_validation', 'scheduled__2024-05-17T00:00:00+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmpgoi5xlay']
[2024-05-18T02:06:38.347+0000] {standard_task_runner.py:91} INFO - Job 173: Subtask branch_based_on_validation
[2024-05-18T02:06:38.521+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation scheduled__2024-05-17T00:00:00+00:00 [running]> on host 5ee845ef4e45
[2024-05-18T02:06:38.727+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='branch_based_on_validation' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T00:00:00+00:00'
[2024-05-18T02:06:38.728+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T02:06:38.761+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-18T02:06:38.786+0000] {python.py:237} INFO - Done. Returned value was: ['send_alerts', 'save_data_errors', 'save_file']
[2024-05-18T02:06:38.787+0000] {branch.py:36} INFO - Branch into ['send_alerts', 'save_data_errors', 'save_file']
[2024-05-18T02:06:38.788+0000] {skipmixin.py:178} INFO - Following branch ['send_alerts', 'save_data_errors', 'save_file']
[2024-05-18T02:06:38.838+0000] {skipmixin.py:246} INFO - Skipping tasks []
[2024-05-18T02:06:38.863+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T02:06:38.901+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_ingestion_pipelines_2, task_id=branch_based_on_validation, run_id=scheduled__2024-05-17T00:00:00+00:00, execution_date=20240517T000000, start_date=20240518T020638, end_date=20240518T020638
[2024-05-18T02:06:38.964+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-18T02:06:39.043+0000] {taskinstance.py:3498} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-05-18T02:06:39.048+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
