[2024-05-18T01:55:58.891+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T01:55:58.935+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T01:55:58.948+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T01:55:58.949+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-05-18T01:55:58.969+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_based_on_validation> on 2024-05-17 00:00:00+00:00
[2024-05-18T01:55:58.978+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=746) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T01:55:58.981+0000] {standard_task_runner.py:63} INFO - Started process 767 to run task
[2024-05-18T01:55:58.981+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'branch_based_on_validation', 'scheduled__2024-05-17T00:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmph7cijj4n']
[2024-05-18T01:55:58.984+0000] {standard_task_runner.py:91} INFO - Job 161: Subtask branch_based_on_validation
[2024-05-18T01:55:59.061+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.branch_based_on_validation scheduled__2024-05-17T00:00:00+00:00 [running]> on host 5ee845ef4e45
[2024-05-18T01:55:59.196+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='branch_based_on_validation' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T00:00:00+00:00'
[2024-05-18T01:55:59.198+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T01:55:59.218+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-18T01:55:59.238+0000] {python.py:237} INFO - Done. Returned value was: ['send_alerts', 'save_data_errors', 'save_file']
[2024-05-18T01:55:59.239+0000] {branch.py:36} INFO - Branch into ['send_alerts', 'save_data_errors', 'save_file']
[2024-05-18T01:55:59.240+0000] {skipmixin.py:178} INFO - Following branch ['send_alerts', 'save_data_errors', 'save_file']
[2024-05-18T01:55:59.292+0000] {skipmixin.py:246} INFO - Skipping tasks []
[2024-05-18T01:55:59.309+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T01:55:59.333+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_ingestion_pipelines_2, task_id=branch_based_on_validation, run_id=scheduled__2024-05-17T00:00:00+00:00, execution_date=20240517T000000, start_date=20240518T015558, end_date=20240518T015559
[2024-05-18T01:55:59.359+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-18T01:55:59.403+0000] {taskinstance.py:3498} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-05-18T01:55:59.407+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
