[2024-05-17T19:58:36.273+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T19:58:36.370+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.send_alerts manual__2024-05-17T12:31:17.083416+00:00 [queued]>
[2024-05-17T19:58:36.395+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.send_alerts manual__2024-05-17T12:31:17.083416+00:00 [queued]>
[2024-05-17T19:58:36.397+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-17T19:58:36.426+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): send_alerts> on 2024-05-17 12:31:17.083416+00:00
[2024-05-17T19:58:36.444+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7390) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T19:58:36.447+0000] {standard_task_runner.py:63} INFO - Started process 7429 to run task
[2024-05-17T19:58:36.450+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'send_alerts', 'manual__2024-05-17T12:31:17.083416+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmp0n8s1qy4']
[2024-05-17T19:58:36.456+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask send_alerts
[2024-05-17T19:58:36.575+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.send_alerts manual__2024-05-17T12:31:17.083416+00:00 [running]> on host e512d0910ba5
[2024-05-17T19:58:36.812+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='send_alerts' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T12:31:17.083416+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T12:31:17.083416+00:00'
[2024-05-17T19:58:36.814+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T19:58:36.921+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T19:58:36.923+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data-ingestion-dag.py", line 102, in send_alerts
    result for result in validation_results["results"] if not result["success"]
                         ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-05-17T19:58:36.943+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_ingestion_pipelines_2, task_id=send_alerts, run_id=manual__2024-05-17T12:31:17.083416+00:00, execution_date=20240517T123117, start_date=20240517T195836, end_date=20240517T195836
[2024-05-17T19:58:36.973+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 45 for task send_alerts (string indices must be integers, not 'str'; 7429)
[2024-05-17T19:58:37.026+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-17T19:58:37.048+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
