[2024-05-16T21:51:49.262+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T21:51:49.310+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.read_data scheduled__2024-05-15T00:00:00+00:00 [queued]>
[2024-05-16T21:51:49.323+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.read_data scheduled__2024-05-15T00:00:00+00:00 [queued]>
[2024-05-16T21:51:49.324+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-16T21:51:49.350+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): read_data> on 2024-05-15 00:00:00+00:00
[2024-05-16T21:51:49.362+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=286) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-16T21:51:49.364+0000] {standard_task_runner.py:63} INFO - Started process 301 to run task
[2024-05-16T21:51:49.365+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'read_data', 'scheduled__2024-05-15T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmp0gn3jxpu']
[2024-05-16T21:51:49.367+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask read_data
[2024-05-16T21:51:49.449+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.read_data scheduled__2024-05-15T00:00:00+00:00 [running]> on host 2fc1c160da1e
[2024-05-16T21:51:49.589+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='read_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-15T00:00:00+00:00'
[2024-05-16T21:51:49.591+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T21:51:49.630+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T21:51:49.631+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data-ingestion-dag.py", line 40, in read_data
    files = [file for file in os.listdir(RAW_DATA_PATH) if file.endswith('.csv')]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/raw-data'
[2024-05-16T21:51:49.647+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_ingestion_pipelines_2, task_id=read_data, run_id=scheduled__2024-05-15T00:00:00+00:00, execution_date=20240515T000000, start_date=20240516T215149, end_date=20240516T215149
[2024-05-16T21:51:49.669+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task read_data ([Errno 2] No such file or directory: '/opt/airflow/dags/raw-data'; 301)
[2024-05-16T21:51:49.700+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-16T21:51:49.765+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T21:51:49.779+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
