[2024-05-18T00:00:35.856+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T00:00:35.905+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.save_file scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T00:00:35.924+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_pipelines_2.save_file scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-05-18T00:00:35.927+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-18T00:00:35.951+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): save_file> on 2024-05-17 00:00:00+00:00
[2024-05-18T00:00:35.964+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=22463) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T00:00:35.967+0000] {standard_task_runner.py:63} INFO - Started process 22489 to run task
[2024-05-18T00:00:35.967+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_pipelines_2', 'save_file', 'scheduled__2024-05-17T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/data-ingestion-dag.py', '--cfg-path', '/tmp/tmphxu3q0he']
[2024-05-18T00:00:35.968+0000] {standard_task_runner.py:91} INFO - Job 122: Subtask save_file
[2024-05-18T00:00:36.056+0000] {task_command.py:426} INFO - Running <TaskInstance: data_ingestion_pipelines_2.save_file scheduled__2024-05-17T00:00:00+00:00 [running]> on host e512d0910ba5
[2024-05-18T00:00:36.203+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_pipelines_2' AIRFLOW_CTX_TASK_ID='save_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T00:00:00+00:00'
[2024-05-18T00:00:36.205+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T00:00:36.273+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T00:00:36.274+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data-ingestion-dag.py", line 175, in save_file
    for result in validation_results["results"]:
                  ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-05-18T00:00:36.291+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_ingestion_pipelines_2, task_id=save_file, run_id=scheduled__2024-05-17T00:00:00+00:00, execution_date=20240517T000000, start_date=20240518T000035, end_date=20240518T000036
[2024-05-18T00:00:36.314+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 122 for task save_file (string indices must be integers, not 'str'; 22489)
[2024-05-18T00:00:36.344+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-18T00:00:36.390+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T00:00:36.394+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
